FROM node:8-alpine

RUN apk --no-cache upgrade && apk add --no-cache tini

WORKDIR /opt/taurus

COPY  ./ /opt/taurus

EXPOSE 80
EXPOSE 443

USER node

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npm", "start"]
